name: Simple Workflow

on: 
  schedule:
    - cron: '*/10 * * * *'
    workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, World!"
